### ISSUE TITLE
pull request

### ISSUE THREAD

**Issue by qwertzuiop961** [azonalon/prgraas#2]
kann es sein, dass die einstellungen in diesem repo anders sind, als in dem anderen? ich bekomme nämlich die fehlermeldung "it seems you do not have permission to push your changes to this repository"

**Comment by azonalon** [comment]
du darfst auch nicht in meine repo pushen, ist es das was du versucht hast?

**Comment by azonalon** [comment]
du solltest erst meine repo in deine pullen, und dann einen pull request an mich senden, damit ich 
deine updates kriege.
